name: Generador Automático de Feed RSS

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar herramientas necesarias
        run: |
          pip install requests beautifulsoup4

      - name: Ejecutar script raspador
        run: python generate_feed.py

      - name: Guardar cambios del archivo feed.xml en el repositorio
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [ -f feed.xml ]; then
            git add feed.xml
            git commit -m "bot: Actualización de noticias en feed.xml" || exit 0
            git push
          else
            echo "El archivo feed.xml no fue encontrado para realizar el commit."
          fi
